[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["cd services/etl && pip install -r ../../requirements.txt"]

[start]
cmd = "cd services/etl && uvicorn app.main:app --host 0.0.0.0 --port $PORT"

