[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "postgresql"]

[phases.install]
cmds = ["cd services/etl && python3 -m pip install -r ../../requirements.txt"]

[start]
cmd = "cd services/etl && uvicorn app.main:app --host 0.0.0.0 --port $PORT"

