# Railway configuration for AGI Tracker Backend
# Tells Railway this is a Python app in services/etl/

[build]
builder = "NIXPACKS"
buildCommand = "cd services/etl && python3 -m pip install -r ../../requirements.txt"

[deploy]
startCommand = "cd services/etl && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
# Force Python environment (use python3 -m pip instead of bare pip)
nixpkgs = ["python311", "postgresql"]
