# Railway.app configuration for AGI Tracker API
# https://docs.railway.app/deploy/config-as-code

[build]
builder = "DOCKERFILE"
dockerfilePath = "services/etl/Dockerfile"
buildCommand = ""

[deploy]
startCommand = ""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

